//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc()
        {
            this.Bao_Hanh = new HashSet<Bao_Hanh>();
            this.danh_gia = new HashSet<danh_gia>();
            this.Danh_Gia_Trang = new HashSet<Danh_Gia_Trang>();
            this.Dat_Hang = new HashSet<Dat_Hang>();
            this.hang_cho = new HashSet<hang_cho>();
            this.like_DanhGia = new HashSet<like_DanhGia>();
            this.like_Rep_danhGia = new HashSet<like_Rep_danhGia>();
            this.rep_danh_Gia = new HashSet<rep_danh_Gia>();
            this.thongTins = new HashSet<thongTin>();
            this.Tra_Gop = new HashSet<Tra_Gop>();
        }
    
        public string taikhoan { get; set; }
        public string matkhau { get; set; }
        public string hask { get; set; }
        public int phanQuyen { get; set; }
        public string gmail { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<bool> daxoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bao_Hanh> Bao_Hanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danh_gia> danh_gia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danh_Gia_Trang> Danh_Gia_Trang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dat_Hang> Dat_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hang_cho> hang_cho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like_DanhGia> like_DanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like_Rep_danhGia> like_Rep_danhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rep_danh_Gia> rep_danh_Gia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thongTin> thongTins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tra_Gop> Tra_Gop { get; set; }
    }
}
