//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet_LinhKien
    {
        public string tag { get; set; }
        public string noidung { get; set; }
        public Nullable<int> anhsanpham { get; set; }
        public bool da_Xoa { get; set; }
    
        public virtual anhsanpham anhsanpham1 { get; set; }
    }
}
