//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bao_Hanh
    {
        public int id { get; set; }
        public string giamgia { get; set; }
        public Nullable<int> sanpham { get; set; }
        public string acc { get; set; }
        public int soLuong { get; set; }
        public bool daXoa { get; set; }
        public System.DateTime ngay_begin_baoHanh { get; set; }
        public System.DateTime time_baoHanh { get; set; }
    
        public virtual acc acc1 { get; set; }
        public virtual magiamgia magiamgia { get; set; }
        public virtual sanpham sanpham1 { get; set; }
    }
}
