//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_Dong_Ho_CongNghe
    {
        public int id { get; set; }
        public string mau_Sac { get; set; }
        public string man_hinh { get; set; }
        public string congNgheManHinh { get; set; }
        public string KichThucManHinh { get; set; }
        public string doPhanGiai { get; set; }
        public Nullable<int> duongKinhMat { get; set; }
        public string cpu { get; set; }
        public string boNhoTrong { get; set; }
        public string HeDieuHanh { get; set; }
        public string ketNoiHeDieuHanh { get; set; }
        public string congSac { get; set; }
        public Nullable<int> ThoiGianSuDungPin { get; set; }
        public Nullable<int> thoiGianSac { get; set; }
        public Nullable<int> dungLuongPin { get; set; }
        public string theoDoiSucKhoe { get; set; }
        public string HienThiThongBao { get; set; }
        public string TienIchKhac { get; set; }
        public string ketnoi { get; set; }
        public string cammera { get; set; }
        public Nullable<int> dodaiDay { get; set; }
        public Nullable<int> doRongDay { get; set; }
        public string chatlieuday { get; set; }
        public Nullable<bool> daycoThethaoroi { get; set; }
        public string chatlieukhungvien { get; set; }
        public string ngonNgu { get; set; }
        public string khichThuoc { get; set; }
        public Nullable<int> trongLuong { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
