//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_PhuKien_Cammera
    {
        public int id { get; set; }
        public string dophangiai { get; set; }
        public Nullable<int> nguondienvao { get; set; }
        public Nullable<int> tamNhinHongNgoai { get; set; }
        public string hoTroTheNho { get; set; }
        public string hoTroThietBi { get; set; }
        public string khichthuoc { get; set; }
        public Nullable<int> trongluong { get; set; }
        public string nhietdoHoatDong { get; set; }
        public string thuongHieu { get; set; }
        public string nguonGoc { get; set; }
        public string PhuKien { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
