//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_PhuKien_ThietBiMang
    {
        public int id { get; set; }
        public Nullable<int> loai { get; set; }
        public Nullable<int> tocDo { get; set; }
        public Nullable<int> bangTan { get; set; }
        public string cacCongKetNoi { get; set; }
        public string DenBaoHieu { get; set; }
        public string soAngTen { get; set; }
        public Nullable<int> TruyCapToiDa { get; set; }
        public Nullable<int> DoPhuSong { get; set; }
        public string NutBamHoTro { get; set; }
        public string mauSac { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
