//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_PhuKien_ThietBiNho
    {
        public int id { get; set; }
        public int loai { get; set; }
        public string cong { get; set; }
        public Nullable<int> dungluong { get; set; }
        public Nullable<int> tocdodoc { get; set; }
        public Nullable<int> tocdoghi { get; set; }
        public Nullable<int> kichthuoc { get; set; }
        public Nullable<int> trongluong { get; set; }
        public string noisanxuat { get; set; }
        public string thuonghieu { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
