//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_May_Tinh
    {
        public int id { get; set; }
        public string cpu { get; set; }
        public string loaiCPU { get; set; }
        public Nullable<int> tocdocpu { get; set; }
        public Nullable<int> tocdoToida { get; set; }
        public string loaiRam { get; set; }
        public string tocDoBusRam { get; set; }
        public string hoTroRamToiDa { get; set; }
        public string Ram { get; set; }
        public string OCung { get; set; }
        public string kichthuocManHinh { get; set; }
        public string DoPhanGiai { get; set; }
        public string CongNgheManHinh { get; set; }
        public Nullable<bool> ManHinhCamUng { get; set; }
        public string ThietKeCard { get; set; }
        public string cardDoHoa { get; set; }
        public string CongNgheAmThanh { get; set; }
        public string congGiaoTiep { get; set; }
        public string ketnoiKhongday { get; set; }
        public string kheDocTheNho { get; set; }
        public string OdiaQuang { get; set; }
        public string WebCam { get; set; }
        public string TinhNangKhac { get; set; }
        public string DenBanPhm { get; set; }
        public string pin { get; set; }
        public string thongTinPhin { get; set; }
        public string HeDieuHanh { get; set; }
        public string KichThuoc { get; set; }
        public string TrongLuong { get; set; }
        public string ChatLieu { get; set; }
        public string ThoiDiemRaMat { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
