//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_The_cao
    {
        public int id { get; set; }
        public bool SimOrThe { get; set; }
        public Nullable<decimal> sdt { get; set; }
        public Nullable<decimal> maThe { get; set; }
        public Nullable<decimal> seri { get; set; }
        public Nullable<decimal> menhGia { get; set; }
        public string NhaMang { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
