//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_Dien_Thoai
    {
        public int id { get; set; }
        public string mau_Sac { get; set; }
        public string man_hinh { get; set; }
        public string he_dieu_hanh { get; set; }
        public string camera_Truoc { get; set; }
        public string camera_Sau { get; set; }
        public string Loi_san_Pham { get; set; }
        public string di_Kem { get; set; }
        public string ram { get; set; }
        public string cpu { get; set; }
        public int bo_nho { get; set; }
        public string the_nho { get; set; }
        public string sim { get; set; }
        public string doPhanGiai { get; set; }
        public string Man_Hinh_rong { get; set; }
        public string KinhCamUng { get; set; }
        public string chipset { get; set; }
        public string TocDocpu { get; set; }
        public string GPU { get; set; }
        public string DoPhanGiaiCammeraTruoc { get; set; }
        public string VideoCall { get; set; }
        public string ThongTinKhacCamMera { get; set; }
        public string DoPhanGiaiCamerasau { get; set; }
        public string quayPhim { get; set; }
        public string denFlash { get; set; }
        public string chupAnhNangCao { get; set; }
        public string hoTroMang { get; set; }
        public string wifi { get; set; }
        public string GPS { get; set; }
        public string bluetooth { get; set; }
        public string congKetNoi { get; set; }
        public string JackTaiNGhe { get; set; }
        public string ketNoiKhac { get; set; }
        public string thietKe { get; set; }
        public string ChatLieu { get; set; }
        public string KichThuoc { get; set; }
        public string TrongLuong { get; set; }
        public string LoaiPin { get; set; }
        public string CongNghePin { get; set; }
        public int dung_luong_Pin { get; set; }
        public string BaoMat { get; set; }
        public string TinhNangNoiBat { get; set; }
        public string GhiAm { get; set; }
        public string Radio { get; set; }
        public string XemPhim { get; set; }
        public string NGheNHac { get; set; }
        public string ThoiDiemRaMat { get; set; }
        public bool LoaiSanPham { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
