//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_PhuKien_tainghe
    {
        public int id { get; set; }
        public int chungLoai { get; set; }
        public string TuongThich { get; set; }
        public Nullable<int> congXuat { get; set; }
        public string cachKetNoi { get; set; }
        public string PhimDieuKhien { get; set; }
        public string TinhNangKhac { get; set; }
        public Nullable<int> KhoangCachBluetooth { get; set; }
        public string kichThuocSieuTram { get; set; }
        public string KichThuocVeTinh { get; set; }
        public Nullable<int> trongLuong { get; set; }
        public string thuongHieu { get; set; }
        public string XuatSu { get; set; }
        public string BoBanHangChuan { get; set; }
        public string CongSac { get; set; }
        public Nullable<int> ThoiGianSuDung { get; set; }
        public Nullable<int> KetNoiCungLuc { get; set; }
        public Nullable<int> ThoiGianXacDay { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
