//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_PhuKien_CapSac
    {
        public int id { get; set; }
        public Nullable<int> loai { get; set; }
        public Nullable<int> doDaiDay { get; set; }
        public string chucNang { get; set; }
        public string dauvao { get; set; }
        public string dauRa { get; set; }
        public string congNghe { get; set; }
        public string tienIch { get; set; }
        public string ThuongHieu { get; set; }
        public string NguonGoc { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
