//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_PhuKien_PIN
    {
        public int id { get; set; }
        public Nullable<int> HieuXuatXac { get; set; }
        public Nullable<int> dungluong { get; set; }
        public Nullable<int> thoiGianXac { get; set; }
        public string nguonvao { get; set; }
        public string loiPin { get; set; }
        public string congnghe { get; set; }
        public string tienich { get; set; }
        public Nullable<int> trongLuong { get; set; }
        public string thuongHieu { get; set; }
        public string NguonGoc { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
