//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_PhuKien_OpLung
    {
        public int id { get; set; }
        public string DongMay { get; set; }
        public string chatLieu { get; set; }
        public Nullable<int> sanpham { get; set; }
    
        public virtual sanpham sanpham1 { get; set; }
    }
}
