//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danh_gia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danh_gia()
        {
            this.like_DanhGia = new HashSet<like_DanhGia>();
            this.rep_danh_Gia = new HashSet<rep_danh_Gia>();
        }
    
        public int id { get; set; }
        public string noidung { get; set; }
        public Nullable<int> soSao { get; set; }
        public Nullable<int> sanpham { get; set; }
        public string acc { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
    
        public virtual acc acc1 { get; set; }
        public virtual sanpham sanpham1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like_DanhGia> like_DanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rep_danh_Gia> rep_danh_Gia { get; set; }
    }
}
