//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danh_Muc_Theo_Chu_De
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Danh_Muc_Theo_Chu_De()
        {
            this.Danh_Muc_Theo_Chung_loai = new HashSet<Danh_Muc_Theo_Chung_loai>();
        }
    
        public int id { get; set; }
        public string ten_chu_de { get; set; }
        public bool da_xoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danh_Muc_Theo_Chung_loai> Danh_Muc_Theo_Chung_loai { get; set; }
    }
}
