//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class like_DanhGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public like_DanhGia()
        {
            this.like_Rep_danhGia = new HashSet<like_Rep_danhGia>();
        }
    
        public int id { get; set; }
        public Nullable<bool> C_like { get; set; }
        public Nullable<bool> dislike { get; set; }
        public string acc { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public Nullable<int> danhgia { get; set; }
    
        public virtual acc acc1 { get; set; }
        public virtual danh_gia danh_gia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like_Rep_danhGia> like_Rep_danhGia { get; set; }
    }
}
