//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bandiDongEntities : DbContext
    {
        public bandiDongEntities()
            : base("name=bandiDongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acc> accs { get; set; }
        public virtual DbSet<anhsanpham> anhsanphams { get; set; }
        public virtual DbSet<BaiViet_LinhKien> BaiViet_LinhKien { get; set; }
        public virtual DbSet<Bao_Hanh> Bao_Hanh { get; set; }
        public virtual DbSet<chi_tiet_Dien_Thoai> chi_tiet_Dien_Thoai { get; set; }
        public virtual DbSet<chi_tiet_Dong_Ho_CongNghe> chi_tiet_Dong_Ho_CongNghe { get; set; }
        public virtual DbSet<chi_tiet_DongHoThoiTrang> chi_tiet_DongHoThoiTrang { get; set; }
        public virtual DbSet<chi_tiet_May_Tinh> chi_tiet_May_Tinh { get; set; }
        public virtual DbSet<chi_tiet_PhuKien_Cammera> chi_tiet_PhuKien_Cammera { get; set; }
        public virtual DbSet<chi_tiet_PhuKien_CapSac> chi_tiet_PhuKien_CapSac { get; set; }
        public virtual DbSet<chi_tiet_PhuKien_OpLung> chi_tiet_PhuKien_OpLung { get; set; }
        public virtual DbSet<chi_tiet_PhuKien_PIN> chi_tiet_PhuKien_PIN { get; set; }
        public virtual DbSet<chi_tiet_PhuKien_tainghe> chi_tiet_PhuKien_tainghe { get; set; }
        public virtual DbSet<chi_tiet_PhuKien_ThietBiMang> chi_tiet_PhuKien_ThietBiMang { get; set; }
        public virtual DbSet<chi_tiet_PhuKien_ThietBiNho> chi_tiet_PhuKien_ThietBiNho { get; set; }
        public virtual DbSet<chi_tiet_The_cao> chi_tiet_The_cao { get; set; }
        public virtual DbSet<danh_gia> danh_gia { get; set; }
        public virtual DbSet<Danh_Gia_Trang> Danh_Gia_Trang { get; set; }
        public virtual DbSet<Danh_Muc_Theo_Chu_De> Danh_Muc_Theo_Chu_De { get; set; }
        public virtual DbSet<Danh_Muc_Theo_Chung_loai> Danh_Muc_Theo_Chung_loai { get; set; }
        public virtual DbSet<Dat_Hang> Dat_Hang { get; set; }
        public virtual DbSet<Gioi_Thieu_product> Gioi_Thieu_product { get; set; }
        public virtual DbSet<hang_cho> hang_cho { get; set; }
        public virtual DbSet<like_DanhGia> like_DanhGia { get; set; }
        public virtual DbSet<like_Rep_danhGia> like_Rep_danhGia { get; set; }
        public virtual DbSet<magiamgia> magiamgias { get; set; }
        public virtual DbSet<nhacungCap> nhacungCaps { get; set; }
        public virtual DbSet<rep_danh_Gia> rep_danh_Gia { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<thongTin> thongTins { get; set; }
        public virtual DbSet<Tra_Gop> Tra_Gop { get; set; }
    
        [DbFunction("bandiDongEntities", "F_layNgauNhienSanPham")]
        public virtual IQueryable<F_layNgauNhienSanPham_Result> F_layNgauNhienSanPham(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layNgauNhienSanPham_Result>("[bandiDongEntities].[F_layNgauNhienSanPham](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_layNgauNhienSanPhamChungLoaiDienThoai")]
        public virtual IQueryable<F_layNgauNhienSanPhamChungLoaiDienThoai_Result> F_layNgauNhienSanPhamChungLoaiDienThoai(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layNgauNhienSanPhamChungLoaiDienThoai_Result>("[bandiDongEntities].[F_layNgauNhienSanPhamChungLoaiDienThoai](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_layNgauNhienSanPhamChungLoaiDongHo")]
        public virtual IQueryable<F_layNgauNhienSanPhamChungLoaiDongHo_Result> F_layNgauNhienSanPhamChungLoaiDongHo(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layNgauNhienSanPhamChungLoaiDongHo_Result>("[bandiDongEntities].[F_layNgauNhienSanPhamChungLoaiDongHo](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_layNgauNhienSanPhamChungLoaiMayTinh")]
        public virtual IQueryable<F_layNgauNhienSanPhamChungLoaiMayTinh_Result> F_layNgauNhienSanPhamChungLoaiMayTinh(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layNgauNhienSanPhamChungLoaiMayTinh_Result>("[bandiDongEntities].[F_layNgauNhienSanPhamChungLoaiMayTinh](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_layNgauNhienSanPhamChungLoaiPhuKien")]
        public virtual IQueryable<F_layNgauNhienSanPhamChungLoaiPhuKien_Result> F_layNgauNhienSanPhamChungLoaiPhuKien(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layNgauNhienSanPhamChungLoaiPhuKien_Result>("[bandiDongEntities].[F_layNgauNhienSanPhamChungLoaiPhuKien](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_layNgauNhienSanPhamChungLoaiSimThe")]
        public virtual IQueryable<F_layNgauNhienSanPhamChungLoaiSimThe_Result> F_layNgauNhienSanPhamChungLoaiSimThe(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layNgauNhienSanPhamChungLoaiSimThe_Result>("[bandiDongEntities].[F_layNgauNhienSanPhamChungLoaiSimThe](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_layNgauNhienSanPhamChungLoaiTablet")]
        public virtual IQueryable<F_layNgauNhienSanPhamChungLoaiTablet_Result> F_layNgauNhienSanPhamChungLoaiTablet(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layNgauNhienSanPhamChungLoaiTablet_Result>("[bandiDongEntities].[F_layNgauNhienSanPhamChungLoaiTablet](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_LaySanPhamNoiBatChung")]
        public virtual IQueryable<F_LaySanPhamNoiBatChung_Result> F_LaySanPhamNoiBatChung(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LaySanPhamNoiBatChung_Result>("[bandiDongEntities].[F_LaySanPhamNoiBatChung](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_LaySanPhamNoiBatChungDienThoai")]
        public virtual IQueryable<F_LaySanPhamNoiBatChungDienThoai_Result> F_LaySanPhamNoiBatChungDienThoai(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LaySanPhamNoiBatChungDienThoai_Result>("[bandiDongEntities].[F_LaySanPhamNoiBatChungDienThoai](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_LaySanPhamNoiBatChungDongHo")]
        public virtual IQueryable<F_LaySanPhamNoiBatChungDongHo_Result> F_LaySanPhamNoiBatChungDongHo(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LaySanPhamNoiBatChungDongHo_Result>("[bandiDongEntities].[F_LaySanPhamNoiBatChungDongHo](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_LaySanPhamNoiBatChungMayTinh")]
        public virtual IQueryable<F_LaySanPhamNoiBatChungMayTinh_Result> F_LaySanPhamNoiBatChungMayTinh(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LaySanPhamNoiBatChungMayTinh_Result>("[bandiDongEntities].[F_LaySanPhamNoiBatChungMayTinh](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_LaySanPhamNoiBatChungphukien")]
        public virtual IQueryable<F_LaySanPhamNoiBatChungphukien_Result> F_LaySanPhamNoiBatChungphukien(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LaySanPhamNoiBatChungphukien_Result>("[bandiDongEntities].[F_LaySanPhamNoiBatChungphukien](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_LaySanPhamNoiBatChungSimThe")]
        public virtual IQueryable<F_LaySanPhamNoiBatChungSimThe_Result> F_LaySanPhamNoiBatChungSimThe(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LaySanPhamNoiBatChungSimThe_Result>("[bandiDongEntities].[F_LaySanPhamNoiBatChungSimThe](@so)", soParameter);
        }
    
        [DbFunction("bandiDongEntities", "F_LaySanPhamNoiBatChungtablet")]
        public virtual IQueryable<F_LaySanPhamNoiBatChungtablet_Result> F_LaySanPhamNoiBatChungtablet(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LaySanPhamNoiBatChungtablet_Result>("[bandiDongEntities].[F_LaySanPhamNoiBatChungtablet](@so)", soParameter);
        }
    }
}
