//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhacungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhacungCap()
        {
            this.Danh_Gia_Trang = new HashSet<Danh_Gia_Trang>();
            this.sanphams = new HashSet<sanpham>();
        }
    
        public int id { get; set; }
        public int idncc { get; set; }
        public string Avatar { get; set; }
        public string TenTrang { get; set; }
        public System.DateTime thoi_Gian_vao { get; set; }
        public Nullable<bool> da_Xoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danh_Gia_Trang> Danh_Gia_Trang { get; set; }
        public virtual thongTin thongTin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
