//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_danh_Gia
    {
        public int id { get; set; }
        public string noidung { get; set; }
        public string acc { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public Nullable<int> danhgia { get; set; }
    
        public virtual acc acc1 { get; set; }
        public virtual danh_gia danh_gia { get; set; }
    }
}
