//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.Bao_Hanh1 = new HashSet<Bao_Hanh>();
            this.chi_tiet_Dien_Thoai = new HashSet<chi_tiet_Dien_Thoai>();
            this.chi_tiet_Dong_Ho_CongNghe = new HashSet<chi_tiet_Dong_Ho_CongNghe>();
            this.chi_tiet_DongHoThoiTrang = new HashSet<chi_tiet_DongHoThoiTrang>();
            this.chi_tiet_May_Tinh = new HashSet<chi_tiet_May_Tinh>();
            this.chi_tiet_PhuKien_Cammera = new HashSet<chi_tiet_PhuKien_Cammera>();
            this.chi_tiet_PhuKien_CapSac = new HashSet<chi_tiet_PhuKien_CapSac>();
            this.chi_tiet_PhuKien_OpLung = new HashSet<chi_tiet_PhuKien_OpLung>();
            this.chi_tiet_PhuKien_PIN = new HashSet<chi_tiet_PhuKien_PIN>();
            this.chi_tiet_PhuKien_tainghe = new HashSet<chi_tiet_PhuKien_tainghe>();
            this.chi_tiet_PhuKien_ThietBiMang = new HashSet<chi_tiet_PhuKien_ThietBiMang>();
            this.chi_tiet_PhuKien_ThietBiNho = new HashSet<chi_tiet_PhuKien_ThietBiNho>();
            this.chi_tiet_The_cao = new HashSet<chi_tiet_The_cao>();
            this.danh_gia = new HashSet<danh_gia>();
            this.Dat_Hang = new HashSet<Dat_Hang>();
            this.Gioi_Thieu_product = new HashSet<Gioi_Thieu_product>();
            this.hang_cho = new HashSet<hang_cho>();
            this.magiamgias = new HashSet<magiamgia>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public decimal gia { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<int> soLuongconlai { get; set; }
        public int bao_hanh { get; set; }
        public Nullable<int> anhsanpham { get; set; }
        public Nullable<int> Danh_Muc_Theo_Chung_loai { get; set; }
        public Nullable<int> nhacungCap { get; set; }
        public Nullable<bool> daxoa { get; set; }
    
        public virtual anhsanpham anhsanpham1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bao_Hanh> Bao_Hanh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_Dien_Thoai> chi_tiet_Dien_Thoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_Dong_Ho_CongNghe> chi_tiet_Dong_Ho_CongNghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_DongHoThoiTrang> chi_tiet_DongHoThoiTrang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_May_Tinh> chi_tiet_May_Tinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_PhuKien_Cammera> chi_tiet_PhuKien_Cammera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_PhuKien_CapSac> chi_tiet_PhuKien_CapSac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_PhuKien_OpLung> chi_tiet_PhuKien_OpLung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_PhuKien_PIN> chi_tiet_PhuKien_PIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_PhuKien_tainghe> chi_tiet_PhuKien_tainghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_PhuKien_ThietBiMang> chi_tiet_PhuKien_ThietBiMang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_PhuKien_ThietBiNho> chi_tiet_PhuKien_ThietBiNho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_The_cao> chi_tiet_The_cao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danh_gia> danh_gia { get; set; }
        public virtual Danh_Muc_Theo_Chung_loai Danh_Muc_Theo_Chung_loai1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dat_Hang> Dat_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gioi_Thieu_product> Gioi_Thieu_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hang_cho> hang_cho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<magiamgia> magiamgias { get; set; }
        public virtual nhacungCap nhacungCap1 { get; set; }
    }
}
