//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDongTrongToi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tra_Gop
    {
        public int id { get; set; }
        public decimal Total_money { get; set; }
        public decimal money_DaThanhToan { get; set; }
        public int percent_Number { get; set; }
        public System.DateTime time_Begin { get; set; }
        public System.DateTime time_update { get; set; }
        public string sotienLanLuot { get; set; }
        public System.DateTime time_end { get; set; }
        public Nullable<int> sanpham { get; set; }
        public string acc { get; set; }
        public bool da_xoa { get; set; }
    
        public virtual acc acc1 { get; set; }
        public virtual anhsanpham anhsanpham { get; set; }
    }
}
